name: Chess4kids
favicon: null
layout_spectrum: 0.6484510262962431
typography_spectrum: 0.9370699007995427
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.03240954619832337
  lightness: 0.2043217953760177
  saturation: 0.46043176553212106
  rhythmicContrast: 0.28789644432254136
purpose: []
